[ destination.snowflake.credentials]
database = "ALUMNO5_DEV_BRONZE_DB"
password = "Dame_Trabajo03"
username = "ALUMNO5_DBT"
host = "HHFXICV-CIVICAPARTNER"
warehouse = "WH_CURSO_DATA_ENGINEERING"
role = "CURSO_DATA_ENGINEERING"
